# 01 – Data Preprocessing

## Objective
Prepare and clean U.S. natality data for downstream clustering, statistical analysis, and predictive modeling.

## Key Tasks
- Handle missing and unknown values
- Encode categorical variables
- Engineer derived features
- Prepare final dataset for modeling

## Input
Raw birth data dataset

## Output
Cleaned dataset ready for PCA and modeling

# **Import Data + Libraries**

In [ ]:
# Import google drive
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
# Import libraries/packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns/rows
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Capstone/natality2024us.csv')
raw_data = pd.DataFrame(data)
display(raw_data.head())

/tmp/ipykernel_18674/3261334359.py:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('/content/drive/MyDrive/Capstone/natality2024us.csv')

,dob_yy,dob_mm,dob_tt,dob_wk,bfacil,f_bfacil,bfacil3,mage_impflg,mage_repflg,mager,mager14,mager9,mbstate_rec,restatus,mrace31,mrace6,mrace15,mraceimp,mhispx,mhisp_r,f_mhisp,mracehisp,mar_p,dmar,mar_imp,f_mar_p,meduc,f_meduc,fagerpt_flg,fagecomb,fagerec11,frace31,frace6,frace15,fhispx,fhisp_r,f_fhisp,fracehisp,feduc,f_feduc,priorlive,priordead,priorterm,lbo_rec,tbo_rec,illb_r,illb_r11,ilop_r,ilop_r11,ilp_r,ilp_r11,precare,f_mpcb,precare5,previs,previs_rec,f_tpcv,wic,f_wic,cig_0,cig_1,cig_2,cig_3,cig0_r,cig1_r,cig2_r,cig3_r,f_cigs_0,f_cigs_1,f_cigs_2,f_cigs_3,cig_rec,f_tobaco,m_ht_in,f_m_ht,bmi,bmi_r,pwgt_r,f_pwgt,dwgt_r,f_dwgt,wtgain,wtgain_rec,f_wtgain,rf_pdiab,rf_gdiab,rf_phype,rf_ghype,rf_ehype,rf_ppterm,f_rf_pdiab,f_rf_gdiab,f_rf_phyper,f_rf_ghyper,f_rf_eclamp,f_rf_ppb,rf_inftr,rf_fedrg,rf_artec,f_rf_inft,f_rf_inf_drg,f_rf_inf_art,rf_cesar,rf_cesarn,f_rf_cesar,f_rf_ncesar,no_risks,ip_gon,ip_syph,ip_chlam,ip_hepb,ip_hepc,f_ip_gonor,f_ip_syph,f_ip_chlam,f_ip_hepatb,f_ip_hepatc,no_infec,ob_ecvs,ob_ecvf,f_ob_succ,f_ob_fail,ld_indl,ld_augm,ld_ster,ld_antb,ld_chor,ld_anes,f_ld_indl,f_ld_augm,f_ld_ster,f_ld_antb,f_ld_chor,f_ld_anes,no_lbrdlv,me_pres,me_rout,me_trial,f_me_pres,f_me_rout,f_me_trial,rdmeth_rec,dmeth_rec,f_dmeth_rec,mm_mtr,mm_plac,mm_rupt,mm_uhyst,mm_aicu,f_mm_mtr,f_mm_,f_mm_rupt,f_mm_uhyst,f_mm_aicu,no_mmorb,attend,mtran,pay,pay_rec,f_pay,f_pay_rec,apgar5,apgar5r,f_apgar5,apgar10,apgar10r,dplural,imp_plur,setorder_r,sex,imp_sex,dlmp_mm,dlmp_yy,compgst_imp,obgest_flg,combgest,gestrec10,gestrec3,lmpused,oegest_comb,oegest_r10,oegest_r3,dbwt,bwtr12,bwtr4,ab_aven1,ab_aven6,ab_nicu,ab_surf,ab_anti,ab_seiz,f_ab_vent,f_ab_vent6,f_ab_niuc,f_ab_surfac,f_ab_antibio,f_ab_seiz,no_abnorm,ca_anen,ca_mnsb,ca_cchd,ca_cdh,ca_omph,ca_gast,f_ca_anen,f_ca_menin,f_ca_heart,f_ca_hernia,f_ca_ompha,f_ca_gastro,ca_limb,ca_cleft,ca_clpal,ca_down,ca_disor,ca_hypo,f_ca_limb,f_ca_cleftlp,f_ca_cleft,f_ca_downs,f_ca_chrom,f_ca_hypos,no_congen,itran,ilive,bfed,f_bfed,octerr,ocntyfips,ocntypop,mbcntry,mrcntry,mrterr,rcnty,rcnty_pop,rcity_pop,rectype,record_id
0,2024,1,501,2,1,1,1,NaN,NaN,30,10,5,1,1,2,2,2,NaN,0,0,1,2,X,1.0,NaN,1,3,1,NaN,30,5,2,2,2,0,0,1,2,4,1,1,0,0,2,2,30.0,4.0,888,88,30.0,4.0,3,1,1,8,5,1,N,1,0,0,0,0,0,0,0,0,1,1,1,1,N,1,66,1,20.799999,2,129,1,133,1,4,1,1,N,N,N,N,N,N,1,1,1,1,1,1,N,X,X,1,1,1,N,0,1,1,1,N,N,N,N,N,1,1,1,1,1,1,N,N,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,1,1,X,1,1,1,1,1,1,N,N,N,N,N,1,1,1,1,1,1,1,N,5,4,1,1,8,3,1,88,5,1,NaN,9,F,NaN,4,2023,NaN,NaN,38,6,2,NaN,38,6,2,2897,6,3,N,N,N,N,N,N,1,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,N,Y,Y,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2024,1,509,3,1,1,1,NaN,NaN,28,9,4,1,1,13,6,15,NaN,0,0,1,6,X,1.0,NaN,1,6,1,NaN,28,4,10,6,15,1,1,1,7,3,1,0,0,0,1,1,888.0,88.0,888,88,888.0,88.0,3,1,1,13,8,1,N,1,0,0,0,0,0,0,0,0,1,1,1,1,N,1,67,1,20.400000,2,130,1,170,1,40,4,1,N,N,N,N,N,N,1,1,1,1,1,1,N,X,X,1,1,1,N,0,1,1,1,N,N,N,N,N,1,1,1,1,1,1,N,N,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,1,1,X,1,1,1,1,1,1,N,N,N,N,N,1,1,1,1,1,1,1,N,4,4,1,1,10,4,1,88,5,1,NaN,9,F,NaN,4,2023,NaN,NaN,38,6,2,NaN,38,6,2,3175,7,3,N,N,N,N,N,N,1,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,N,Y,Y,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2024,1,525,3,1,1,1,NaN,NaN,41,12,7,1,1,1,1,1,NaN,0,0,1,1,X,1.0,NaN,1,6,1,NaN,35,6,1,1,1,0,0,1,1,3,1,6,0,2,7,8,84.0,8.0,999,99,999.0,99.0,2,1,1,11,7,1,N,1,0,0,0,0,0,0,0,0,1,1,1,1,N,1,67,1,22.700001,2,145,1,173,1,28,3,1,N,N,N,N,N,Y,1,1,1,1,1,1,N,X,X,1,1,1,Y,2,1,1,0,N,N,N,N,N,1,1,1,1,1,1,N,N,1,1,N,Y,N,Y,N,Y,1,1,1,1,1,1,0,1,1,X,1,1,1,2,1,1,N,N,N,N,N,1,1,1,1,1,1,1,N,1,1,1,1,9,4,1,88,5,1,NaN,9,M,NaN,4,2023,NaN,NaN,37,6,2,NaN,37,6,2,2095,5,2,N,N,N,N,N,N,1,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,Y,Y,Y,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,2024,1,1910,2,2,1,2,NaN,NaN,29,9,4,1,2,1,1,1,NaN,0,0,1,1,X,1.0,NaN,1,4,1,NaN,30,5,1,1,1,0,0,1,1,3,1,2,0,0,3,3,49.0,6.0,888,88,49.0,6.0,3,1,1,10,6,1,N,1,0,0,0,0,0,0,0,0,1,1,1,1,N,1,61,1,26.400000,3,140,1,999,1,99,9,1,N,N,N,N,N,N,1,1,1,1,1,1,N,X,X,1,1,1,N,0,1,1,1,N,N,N,N,N,1,1,1,1,1,1,N,N,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,1,1,X,1,1,1,1,1,1,N,N,N,N,N,1,1,1,1,1,1,4,N,1,1,1,1,10,4,1,88,5,1,NaN,9,M,NaN,4,2023,NaN,NaN,38,6,2,NaN,39,7,2,3078,7,3,N,N,N,N,N,N,1,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,N,Y,Y,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,2024,1,2241,2,1,1,1,NaN,NaN,28,9,4,1,1,1,1,1,NaN,0,0,1,1,X,1.0,NaN,1,6,1,NaN,29,4,1,1,1,0,0,1,1,4,1,1,0,2,2,4,17.0,2.0,11,1,11.0,1.0,2,1,1,13,8,1,N,1,0,0,0,0,0,0,0,0,1,1,1,1,N,1,64,1,21.500000,2,125,1,156,1,31,4,1,N,N,N,N,N,Y,1,1,1,1,1,1,N,X,X,1,1,1,N,0,1,1,0,N,N,N,N,N,1,1,1,1,1,1,N,N,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,1,1,X,1,1,1,1,1,1,N,N,N,N,N,1,1,1,1,1,1,3,N,2,2,1,1,9,4,1,88,5,1,NaN,9,F,NaN,4,2023,NaN,NaN,39,7,2,NaN,36,5,1,3070,7,3,N,N,N,N,N,N,1,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,N,N,N,N,N,N,1,1,1,1,1,1,1,N,Y,Y,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [ ]:
raw_data.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3638436 entries, 0 to 3638435
Data columns (total 238 columns):
 #    Column        Dtype
---   ------        -----
 0    dob_yy        int64
 1    dob_mm        int64
 2    dob_tt        int64
 3    dob_wk        int64
 4    bfacil        int64
 5    f_bfacil      int64
 6    bfacil3       int64
 7    mage_impflg   float64
 8    mage_repflg   float64
 9    mager         int64
 10   mager14       int64
 11   mager9        int64
 12   mbstate_rec   int64
 13   restatus      int64
 14   mrace31       int64
 15   mrace6        int64
 16   mrace15       int64
 17   mraceimp      float64
 18   mhispx        int64
 19   mhisp_r       int64
 20   f_mhisp       int64
 21   mracehisp     int64
 22   mar_p         object
 23   dmar          float64
 24   mar_imp       float64
 25   f_mar_p       int64
 26   meduc         int64
 27   f_meduc       int64
 28   fagerpt_flg   float64
 29   fagecomb      int64
 30   fagerec11     int64
 31   frace31       int64
 32   frace6        int64
 33   frace15       int64
 34   fhispx        int64
 35   fhisp_r       int64
 36   f_fhisp       int64
 37   fracehisp     int64
 38   feduc         int64
 39   f_feduc       int64
 40   priorlive     int64
 41   priordead     int64
 42   priorterm     int64
 43   lbo_rec       int64
 44   tbo_rec       int64
 45   illb_r        float64
 46   illb_r11      float64
 47   ilop_r        int64
 48   ilop_r11      int64
 49   ilp_r         float64
 50   ilp_r11       float64
 51   precare       int64
 52   f_mpcb        int64
 53   precare5      int64
 54   previs        int64
 55   previs_rec    int64
 56   f_tpcv        int64
 57   wic           object
 58   f_wic         int64
 59   cig_0         int64
 60   cig_1         int64
 61   cig_2         int64
 62   cig_3         int64
 63   cig0_r        int64
 64   cig1_r        int64
 65   cig2_r        int64
 66   cig3_r        int64
 67   f_cigs_0      int64
 68   f_cigs_1      int64
 69   f_cigs_2      int64
 70   f_cigs_3      int64
 71   cig_rec       object
 72   f_tobaco      int64
 73   m_ht_in       int64
 74   f_m_ht        int64
 75   bmi           float64
 76   bmi_r         int64
 77   pwgt_r        int64
 78   f_pwgt        int64
 79   dwgt_r        int64
 80   f_dwgt        int64
 81   wtgain        int64
 82   wtgain_rec    int64
 83   f_wtgain      int64
 84   rf_pdiab      object
 85   rf_gdiab      object
 86   rf_phype      object
 87   rf_ghype      object
 88   rf_ehype      object
 89   rf_ppterm     object
 90   f_rf_pdiab    int64
 91   f_rf_gdiab    int64
 92   f_rf_phyper   int64
 93   f_rf_ghyper   int64
 94   f_rf_eclamp   int64
 95   f_rf_ppb      int64
 96   rf_inftr      object
 97   rf_fedrg      object
 98   rf_artec      object
 99   f_rf_inft     int64
 100  f_rf_inf_drg  int64
 101  f_rf_inf_art  int64
 102  rf_cesar      object
 103  rf_cesarn     int64
 104  f_rf_cesar    int64
 105  f_rf_ncesar   int64
 106  no_risks      int64
 107  ip_gon        object
 108  ip_syph       object
 109  ip_chlam      object
 110  ip_hepb       object
 111  ip_hepc       object
 112  f_ip_gonor    int64
 113  f_ip_syph     int64
 114  f_ip_chlam    int64
 115  f_ip_hepatb   int64
 116  f_ip_hepatc   int64
 117  no_infec      int64
 118  ob_ecvs       object
 119  ob_ecvf       object
 120  f_ob_succ     int64
 121  f_ob_fail     int64
 122  ld_indl       object
 123  ld_augm       object
 124  ld_ster       object
 125  ld_antb       object
 126  ld_chor       object
 127  ld_anes       object
 128  f_ld_indl     int64
 129  f_ld_augm     int64
 130  f_ld_ster     int64
 131  f_ld_antb     int64
 132  f_ld_chor     int64
 133  f_ld_anes     int64
 134  no_lbrdlv     int64
 135  me_pres       int64
 136  me_rout       int64
 137  me_trial      object
 138  f_me_pres     int64
 139  f_me_rout     int64
 140  f_me_trial    int64
 141  rdmeth_rec    int64
 142  dmeth_rec     int64
 143  f_dmeth_rec   int64
 144  mm_mtr        object
 145  mm_plac       object
 146  mm_rupt       object
 147  mm_uhyst      object
 148  mm_aicu       object
 149  f_mm_mtr      int64
 150  f_mm_         int64
 151  f_mm_rupt     int64
 152  f_mm_uhyst    int64
 153  f_mm_aicu     int64
 154  no_mmorb      int64
 155  attend        int64
 156  mtran         object
 157  pay           int64
 158  pay_rec       int64
 159  f_pay         int64
 160  f_pay_rec     int64
 161  apgar5        int64
 162  apgar5r       int64
 163  f_apgar5      int64
 164  apgar10       int64
 165  apgar10r      int64
 166  dplural       int64
 167  imp_plur      float64
 168  setorder_r    int64
 169  sex           object
 170  imp_sex       float64
 171  dlmp_mm       int64
 172  dlmp_yy       int64
 173  compgst_imp   float64
 174  obgest_flg    float64
 175  combgest      int64
 176  gestrec10     int64
 177  gestrec3      int64
 178  lmpused       float64
 179  oegest_comb   int64
 180  oegest_r10    int64
 181  oegest_r3     int64
 182  dbwt          int64
 183  bwtr12        int64
 184  bwtr4         int64
 185  ab_aven1      object
 186  ab_aven6      object
 187  ab_nicu       object
 188  ab_surf       object
 189  ab_anti       object
 190  ab_seiz       object
 191  f_ab_vent     int64
 192  f_ab_vent6    int64
 193  f_ab_niuc     int64
 194  f_ab_surfac   int64
 195  f_ab_antibio  int64
 196  f_ab_seiz     int64
 197  no_abnorm     int64
 198  ca_anen       object
 199  ca_mnsb       object
 200  ca_cchd       object
 201  ca_cdh        object
 202  ca_omph       object
 203  ca_gast       object
 204  f_ca_anen     int64
 205  f_ca_menin    int64
 206  f_ca_heart    int64
 207  f_ca_hernia   int64
 208  f_ca_ompha    int64
 209  f_ca_gastro   int64
 210  ca_limb       object
 211  ca_cleft      object
 212  ca_clpal      object
 213  ca_down       object
 214  ca_disor      object
 215  ca_hypo       object
 216  f_ca_limb     int64
 217  f_ca_cleftlp  int64
 218  f_ca_cleft    int64
 219  f_ca_downs    int64
 220  f_ca_chrom    int64
 221  f_ca_hypos    int64
 222  no_congen     int64
 223  itran         object
 224  ilive         object
 225  bfed          object
 226  f_bfed        int64
 227  octerr        float64
 228  ocntyfips     float64
 229  ocntypop      float64
 230  mbcntry       float64
 231  mrcntry       float64
 232  mrterr        float64
 233  rcnty         float64
 234  rcnty_pop     float64
 235  rcity_pop     float64
 236  rectype       float64
 237  record_id     int64
dtypes: float64(26), int64(157), object(55)
memory usage: 6.5+ GB

# **Declare Important Features**

In [ ]:
# Declare needed columns

cluster_vars = ['mager', 'priorlive', 'priordead', 'priorterm', 'rf_cesarn', 'illb_r', 'm_ht_in',
                'bmi', 'wtgain', 'combgest', 'previs', 'cig_0', 'cig_1', 'cig_2', 'cig_3', 'rf_pdiab',
                'rf_gdiab', 'rf_phype', 'rf_ghype','rf_ehype', 'rf_ppterm', 'rf_inftr', 'rf_fedrg',
                'rf_artec', 'ip_gon', 'ip_syph','ip_chlam', 'ip_hepb', 'ip_hepc', 'mracehisp',
                'meduc', 'lbo_rec','tbo_rec', 'precare']

morbidity_vars = ['mm_mtr', 'mm_plac', 'mm_rupt', 'mm_uhyst', 'mm_aicu']

ob_ld_vars = ['ob_ecvs', 'ob_ecvf', 'ld_indl', 'ld_augm', 'ld_ster', 'ld_antb', 'ld_chor', 'ld_anes',
              'me_pres', 'me_rout', 'me_trial', 'rdmeth_rec']

neonatal_vars = ['sex', 'apgar5', 'apgar10', 'dplural', 'dbwt', 'bwtr12', 'ab_aven1', 'ab_aven6',
                 'ab_nicu', 'ab_surf','ab_anti', 'ab_seiz','ca_anen', 'ca_mnsb', 'ca_cchd', 'ca_cdh',
                 'ca_omph','ca_gast', 'ca_limb', 'ca_cleft','ca_clpal', 'ca_hypo']

### dont forget to handle C in variable dictionary for neonatal ###

print(f" Total Number of Columns for Clustering:", len(cluster_vars), "columns")
print(f" Total Number of Columns for Maternal Morbidity:", len(morbidity_vars), "columns")
print(f" Total Number of Columns for Obsestrics + L&D:", len(ob_ld_vars), "columns")
print(f" Total Number of Columns for Neonatal:", len(neonatal_vars), "columns")

 Total Number of Columns for Clustering: 34 columns
 Total Number of Columns for Maternal Morbidity: 5 columns
 Total Number of Columns for Obsestrics + L&D: 12 columns
 Total Number of Columns for Neonatal: 22 columns

# **Clean Data**

## ***Unknown and Not Applicable Data***

### ***Unknown/NA Dictionary***

In [ ]:
# Declare numbers that represent 'unknown' OR 'not applicable' in the dataset
unknown_mapping = {
  5: ['precare5', 'apgar5r', 'apgar10r'],
  6: ['cig0_r', 'cig1_r', 'cig2_r', 'cig3_r'],
  8: ['mracehisp', 'fracehisp'],
  9: ['bfacil', 'meduc', 'fracehisp', 'feduc', 'lbo_rec', 'tbo_rec', 'bmi_r', 'wtgain_rec', 'me_pres',
      'me_rout', 'rdmeth_rec', 'attend', 'pay'],
  11: ['fagerec11'],
  12: ['previs_rec', 'bwtr12'],
  99: ['priorlive', 'priordead', 'priorterm', 'illb_r11', 'fagecomb', 'ilop_r11', 'ilp_r11', 'm_ht_in',
       'cig_0', 'cig_1', 'cig_2', 'cig_3', 'precare', 'previs', 'wtgain', 'rf_cesarn', 'apgar5',
       'apgar10', 'dlmp_mm', 'combgest', 'gestrec10', 'oegest_comb', 'oegest_r10'],
  99.9: ['bmi'],
  999: ['pwgt_r', 'dwgt_r', 'illb_r', 'ilop_r', 'ilp_r'],
  9999: ['dob_tt', 'dbwt'],
  'U': ['wic', 'rf_pdiab', 'rf_gdiab', 'rf_phype', 'rf_ghype', 'rf_ehype', 'rf_ppterm', 'rf_inftr',
        'rf_fedrg', 'rf_artec', 'rf_cesar', 'ip_gon', 'ip_syph', 'ip_chlam', 'ip_hepb', 'ip_hepc',
        'ob_ecvs', 'ob_ecvf', 'ld_indl', 'ld_augm', 'ld_ster', 'ld_antb', 'ld_chor', 'ld_anes',
        'me_trial', 'mm_mtr', 'mm_plac', 'mm_rupt', 'mm_uhyst', 'mm_aicu', 'mtran', 'dlmp_yy',
        'ab_aven1', 'ab_aven6', 'ab_nicu', 'ab_surf', 'ab_anti', 'ab_seiz', 'ca_anen', 'ca_mnsb',
        'ca_cchd', 'ca_cdh', 'ca_omph', 'ca_gast', 'ca_limb', 'ca_cleft', 'ca_clpal', 'ca_down',
        'ca_disor', 'ca_hypo', 'itran', 'bfed'],
  'X': ['rf_fedrg', 'rf_artec', 'me_trial'] # can be made NaN, even though its Not Applicable
}

not_applicable_mapping = {
    888: ['ilp_r', # no previous pregnancy
          'ilop_r', # 1st natality event
          'illb_r'], # 1st live birth
}

In [ ]:
# Create flag for not applicable columns
not_applicable_columns = ['illb_r']

for col in not_applicable_columns:

  raw_data[col] = raw_data[col].replace(888, np.nan)

raw_data.columns

Index(['dob_yy', 'dob_mm', 'dob_tt', 'dob_wk', 'bfacil', 'f_bfacil', 'bfacil3',
       'mage_impflg', 'mage_repflg', 'mager',
       ...
       'ocntyfips', 'ocntypop', 'mbcntry', 'mrcntry', 'mrterr', 'rcnty',
       'rcnty_pop', 'rcity_pop', 'rectype', 'record_id'],
      dtype='object', length=238)

In [ ]:
raw_data['illb_r'].value_counts()

illb_r
999.0    105515
22.0      51326
23.0      50093
21.0      49955
25.0      49123
24.0      49052
26.0      47818
20.0      46835
27.0      46463
28.0      44864
3.0       43630
19.0      43494
29.0      43048
30.0      41996
31.0      40318
18.0      39692
32.0      39225
33.0      38204
17.0      36144
34.0      36126
35.0      33759
16.0      32510
36.0      31551
37.0      30141
15.0      29591
38.0      28937
39.0      27420
14.0      26946
40.0      26209
41.0      25312
13.0      24158
42.0      24068
43.0      23316
44.0      22343
45.0      21820
12.0      21263
46.0      20698
47.0      19737
48.0      19250
49.0      18798
50.0      18375
51.0      17689
52.0      17373
53.0      16739
54.0      16238
55.0      15886
56.0      15495
57.0      15461
11.0      14954
58.0      14760
59.0      13973
60.0      13693
61.0      12883
62.0      12693
63.0      12283
64.0      12057
65.0      11683
66.0      11533
67.0      11195
68.0      10918
69.0      10809
70.0      10420
71.0      10119
72.0       9939
73.0       9583
74.0       9309
76.0       8980
75.0       8980
77.0       8748
78.0       8459
79.0       8388
80.0       8155
81.0       8115
82.0       7884
83.0       7566
84.0       7355
85.0       7163
86.0       7014
87.0       6790
10.0       6654
88.0       6638
89.0       6604
91.0       6332
90.0       6253
92.0       6194
93.0       6093
94.0       5946
95.0       5720
96.0       5633
97.0       5529
98.0       5349
100.0      5196
99.0       5171
102.0      5003
101.0      4874
103.0      4773
104.0      4750
105.0      4616
106.0      4614
107.0      4394
108.0      4367
109.0      4147
110.0      4120
111.0      4079
114.0      3846
112.0      3768
113.0      3744
115.0      3721
117.0      3606
116.0      3574
118.0      3512
119.0      3426
120.0      3251
121.0      3166
122.0      3079
123.0      3005
125.0      2948
124.0      2945
126.0      2784
129.0      2721
127.0      2672
128.0      2604
130.0      2494
131.0      2472
132.0      2442
9.0        2440
136.0      2310
133.0      2303
134.0      2298
135.0      2289
137.0      2184
140.0      2173
139.0      2140
138.0      2116
141.0      2042
142.0      1973
143.0      1947
145.0      1923
144.0      1902
147.0      1807
146.0      1796
150.0      1754
148.0      1745
149.0      1739
151.0      1726
152.0      1617
153.0      1548
154.0      1512
156.0      1497
155.0      1490
157.0      1421
158.0      1415
160.0      1364
159.0      1349
161.0      1297
162.0      1278
163.0      1278
166.0      1216
164.0      1199
165.0      1196
168.0      1162
167.0      1127
169.0      1095
8.0        1090
174.0      1088
170.0      1033
171.0      1015
172.0       994
175.0       988
173.0       980
176.0       931
179.0       919
177.0       917
180.0       877
181.0       864
182.0       857
178.0       855
183.0       783
184.0       776
186.0       775
7.0         771
188.0       747
189.0       734
185.0       732
187.0       695
6.0         677
191.0       666
190.0       658
193.0       618
192.0       611
194.0       603
195.0       583
199.0       560
196.0       553
197.0       542
198.0       535
203.0       520
201.0       499
5.0         487
204.0       481
200.0       481
205.0       465
202.0       465
206.0       419
209.0       412
4.0         411
211.0       394
208.0       389
207.0       381
214.0       362
210.0       358
300.0       348
212.0       347
213.0       329
215.0       326
216.0       312
218.0       293
220.0       291
217.0       277
222.0       264
219.0       258
221.0       252
223.0       246
224.0       242
225.0       236
229.0       220
226.0       219
230.0       216
228.0       211
232.0       206
227.0       193
233.0       185
231.0       185
234.0       163
238.0       163
236.0       161
235.0       158
237.0       149
240.0       146
242.0       141
239.0       132
245.0       132
246.0       128
251.0       125
241.0       124
243.0       118
244.0       116
247.0       108
250.0       106
249.0        97
248.0        97
255.0        94
252.0        89
259.0        89
254.0        87
260.0        87
253.0        86
256.0        85
264.0        84
262.0        84
263.0        79
257.0        77
258.0        69
282.0        63
265.0        63
266.0        63
278.0        61
277.0        59
261.0        58
269.0        57
270.0        57
286.0        54
274.0        54
275.0        53
271.0        51
267.0        49
279.0        46
284.0        46
272.0        46
280.0        45
283.0        44
288.0        44
268.0        44
273.0        43
276.0        42
281.0        42
287.0        41
285.0        40
292.0        38
290.0        33
294.0        30
295.0        27
289.0        27
296.0        23
293.0        23
291.0        23
297.0        20
299.0        18
298.0        15
Name: count, dtype: int64

In [ ]:
# Declare Confirmed and Pending for Down Syndrome/Chromosomal Disorder as a Yes ('Y') based on User Guide
cp2yes = ['ca_down', 'ca_disor']

for col_name in cp2yes:
  raw_data[col_name] = raw_data[col_name].replace('C', 'Y')
  raw_data[col_name] = raw_data[col_name].replace('P', 'Y')

In [ ]:
for code, columns in unknown_mapping.items():
  for col in columns:
    if col in raw_data.columns:
      raw_data[col] = raw_data[col].replace(code, np.nan)

# Verify that codes are converted to Nan
for col in unknown_mapping.values():
    for c in col:
        if c in raw_data.columns:
            print(c)
            print(raw_data[c].value_counts(dropna=False).head())

precare5
precare5
1.0    2692072
2.0     615894
3.0     173329
4.0      86919
NaN      70222
Name: count, dtype: int64
apgar5r
apgar5r
4.0    3014023
3.0     524096
2.0      60961
1.0      21018
NaN      18338
Name: count, dtype: int64
apgar10r
apgar10r
NaN    3593242
3.0      19495
2.0      10899
1.0       8190
4.0       6610
Name: count, dtype: int64
cig0_r
cig0_r
0.0    3511981
2.0      34360
3.0      33766
1.0      33620
NaN      18039
Name: count, dtype: int64
cig1_r
cig1_r
0.0    3536243
2.0      30544
1.0      29979
3.0      20962
NaN      17803
Name: count, dtype: int64
cig2_r
cig2_r
0.0    3547439
1.0      29255
2.0      27652
NaN      17693
3.0      14624
Name: count, dtype: int64
cig3_r
cig3_r
0.0    3533421
NaN      35729
1.0      31117
2.0      24169
3.0      12513
Name: count, dtype: int64
mracehisp
mracehisp
1.0    1784051
7.0     991715
2.0     473624
4.0     227183
6.0      91634
Name: count, dtype: int64
fracehisp
fracehisp
1.0    1622988
7.0     858018
NaN     450549
2.0     409819
4.0     196340
Name: count, dtype: int64
bfacil
bfacil
1.0    3551691
3.0      50532
2.0      23115
4.0       6898
7.0       4256
Name: count, dtype: int64
meduc
meduc
3.0    966082
6.0    808770
4.0    594485
7.0    386783
5.0    290868
Name: count, dtype: int64
fracehisp
fracehisp
1.0    1622988
7.0     858018
NaN     450549
2.0     409819
4.0     196340
Name: count, dtype: int64
feduc
feduc
3.0    992519
6.0    684494
4.0    527252
NaN    458843
7.0    261345
Name: count, dtype: int64
lbo_rec
lbo_rec
1.0    1431410
2.0    1140235
3.0     588075
4.0     263053
5.0     107321
Name: count, dtype: int64
tbo_rec
tbo_rec
1.0    1170741
2.0     990325
3.0     646007
4.0     372858
5.0     200904
Name: count, dtype: int64
bmi_r
bmi_r
2.0    1323134
3.0     993716
4.0     610801
5.0     306265
6.0     222907
Name: count, dtype: int64
wtgain_rec
wtgain_rec
3.0    984248
4.0    795535
5.0    723376
2.0    670308
1.0    355953
Name: count, dtype: int64
me_pres
me_pres
1.0    3438227
2.0     158789
3.0      30960
NaN      10460
Name: count, dtype: int64
me_rout
me_rout
1.0    2359075
4.0    1176845
3.0      82393
2.0      14966
NaN       5157
Name: count, dtype: int64
rdmeth_rec
rdmeth_rec
1.0    2365815
3.0     702624
4.0     473280
2.0      86919
NaN       5157
Name: count, dtype: int64
attend
attend
1.0    2732988
3.0     435179
2.0     376958
4.0      49534
5.0      40534
Name: count, dtype: int64
pay
pay
2.0    1866571
1.0    1445726
3.0     176851
5.0      43841
8.0      40446
Name: count, dtype: int64
fagerec11
fagerec11
5.0    983858
4.0    742169
6.0    705933
3.0    370643
NaN    363459
Name: count, dtype: int64
previs_rec
previs_rec
7.0    943327
6.0    756944
8.0    577982
5.0    368228
9.0    279472
Name: count, dtype: int64
bwtr12
bwtr12
7.0    1422354
8.0     927525
6.0     718584
9.0     224689
5.0     201886
Name: count, dtype: int64
priorlive
priorlive
0.0    1456955
1.0    1131222
2.0     587471
3.0     260542
4.0     104546
Name: count, dtype: int64
priordead
priordead
0.0    3583192
1.0      34442
NaN      14291
2.0       4137
3.0       1023
Name: count, dtype: int64
priorterm
priorterm
0.0    2603545
1.0     655467
2.0     225615
3.0      81305
4.0      30548
Name: count, dtype: int64
illb_r11
illb_r11
88.0    1431410
4.0      509996
8.0      426518
5.0      301552
3.0      281395
Name: count, dtype: int64
fagecomb
fagecomb
NaN     363459
32.0    202172
33.0    201746
31.0    196535
34.0    195097
Name: count, dtype: int64
ilop_r11
ilop_r11
88.0    2603545
NaN      312592
8.0      144736
2.0      144632
1.0      101375
Name: count, dtype: int64
ilp_r11
ilp_r11
88.0    1160487
4.0      473728
NaN      385882
8.0      322218
3.0      306741
Name: count, dtype: int64
m_ht_in
m_ht_in
64.0    524727
63.0    476343
62.0    472073
65.0    435827
66.0    375497
Name: count, dtype: int64
cig_0
cig_0
0.0     3511981
20.0      30036
10.0      26832
NaN       18039
5.0       11709
Name: count, dtype: int64
cig_1
cig_1
0.0     3536243
10.0      24145
20.0      17855
NaN       17803
5.0       11420
Name: count, dtype: int64
cig_2
cig_2
0.0     3547439
10.0      21672
NaN       17693
20.0      12508
5.0       11611
Name: count, dtype: int64
cig_3
cig_3
0.0     3533421
NaN       35729
10.0      19131
5.0       11483
20.0      11037
Name: count, dtype: int64
precare
precare
2.0    1287654
3.0    1253860
4.0     346032
5.0     166721
1.0     150558
Name: count, dtype: int64
previs
previs
12.0    542786
10.0    484607
11.0    400541
13.0    331120
9.0     272337
Name: count, dtype: int64
wtgain
wtgain
30.0    152058
20.0    142658
25.0    123689
NaN     109016
35.0    104120
Name: count, dtype: int64
rf_cesarn
rf_cesarn
0.0    3070550
1.0     389549
2.0     123793
3.0      35357
4.0       8560
Name: count, dtype: int64
apgar5
apgar5
9.0     2951580
8.0      437574
7.0       86522
10.0      62443
6.0       34221
Name: count, dtype: int64
apgar10
apgar10
88.0    3572340
NaN       20902
7.0        9996
8.0        9499
9.0        6210
Name: count, dtype: int64
dlmp_mm
dlmp_mm
12.0    310430
11.0    303450
10.0    302214
1.0     296880
8.0     288724
Name: count, dtype: int64
combgest
combgest
39.0    1099009
40.0     633697
38.0     603201
37.0     409155
41.0     254453
Name: count, dtype: int64
gestrec10
gestrec10
7.0    1099009
6.0    1012356
8.0     633697
5.0     317723
9.0     254453
Name: count, dtype: int64
oegest_comb
oegest_comb
39.0    1358692
38.0     636340
40.0     625892
37.0     463390
41.0     162397
Name: count, dtype: int64
oegest_r10
oegest_r10
7.0    1358692
6.0    1099730
8.0     625892
5.0     279144
9.0     162397
Name: count, dtype: int64
bmi
bmi
99.900002    88890
26.600000    68021
28.299999    62792
27.400000    44414
25.799999    43431
Name: count, dtype: int64
pwgt_r
pwgt_r
130.0    135738
150.0    130863
140.0    124462
160.0    110759
135.0    105005
Name: count, dtype: int64
dwgt_r
dwgt_r
180.0    67195
160.0    65055
170.0    63111
190.0    55827
165.0    54047
Name: count, dtype: int64
illb_r
illb_r
NaN     1536926
22.0      51326
23.0      50093
21.0      49955
25.0      49123
Name: count, dtype: int64
ilop_r
ilop_r
888.0    2603545
NaN       312592
11.0       39189
12.0       36650
10.0       35431
Name: count, dtype: int64
ilp_r
ilp_r
888.0    1160487
NaN       385882
12.0       54650
21.0       53444
22.0       53124
Name: count, dtype: int64
dob_tt
dob_tt
805.0    4898
800.0    4887
808.0    4867
802.0    4828
806.0    4814
Name: count, dtype: int64
dbwt
dbwt
3260.0    34392
3430.0    32893
3090.0    29849
3600.0    27353
2920.0    23672
Name: count, dtype: int64
wic
wic
N      2444756
Y      1150374
NaN      43306
Name: count, dtype: int64
rf_pdiab
rf_pdiab
N      3583223
Y        47719
NaN       7494
Name: count, dtype: int64
rf_gdiab
rf_gdiab
N      3323369
Y       307573
NaN       7494
Name: count, dtype: int64
rf_phype
rf_phype
N      3509522
Y       121420
NaN       7494
Name: count, dtype: int64
rf_ghype
rf_ghype
N      3253150
Y       377792
NaN       7494
Name: count, dtype: int64
rf_ehype
rf_ehype
N      3622720
Y         8222
NaN       7494
Name: count, dtype: int64
rf_ppterm
rf_ppterm
N      3485875
Y       145067
NaN       7494
Name: count, dtype: int64
rf_inftr
rf_inftr
N      3539601
Y        91341
NaN       7494
Name: count, dtype: int64
rf_fedrg
rf_fedrg
NaN    3549214
N        60671
Y        28551
Name: count, dtype: int64
rf_artec
rf_artec
NaN    3549214
Y        69722
N        19500
Name: count, dtype: int64
rf_cesar
rf_cesar
N      3070550
Y       560392
NaN       7494
Name: count, dtype: int64
ip_gon
ip_gon
N      3616022
NaN      14515
Y         7899
Name: count, dtype: int64
ip_syph
ip_syph
N      3610952
NaN      14515
Y        12969
Name: count, dtype: int64
ip_chlam
ip_chlam
N      3563793
Y        60128
NaN      14515
Name: count, dtype: int64
ip_hepb
ip_hepb
N      3617916
NaN      14515
Y         6005
Name: count, dtype: int64
ip_hepc
ip_hepc
N      3610695
NaN      14515
Y        13226
Name: count, dtype: int64
ob_ecvs
ob_ecvs
N      3624129
NaN       7733
Y         6574
Name: count, dtype: int64
ob_ecvf
ob_ecvf
N      3624494
NaN       7733
Y         6209
Name: count, dtype: int64
ld_indl
ld_indl
N      2404465
Y      1231717
NaN       2254
Name: count, dtype: int64
ld_augm
ld_augm
N      2873425
Y       762757
NaN       2254
Name: count, dtype: int64
ld_ster
ld_ster
N      3504958
Y       131224
NaN       2254
Name: count, dtype: int64
ld_antb
ld_antb
N      2741121
Y       895061
NaN       2254
Name: count, dtype: int64
ld_chor
ld_chor
N      3569893
Y        66289
NaN       2254
Name: count, dtype: int64
ld_anes
ld_anes
Y      2841108
N       795074
NaN       2254
Name: count, dtype: int64
me_trial
me_trial
NaN    2472366
N       837948
Y       328122
Name: count, dtype: int64
mm_mtr
mm_mtr
N      3605218
Y        21140
NaN      12078
Name: count, dtype: int64
mm_plac
mm_plac
N      3598112
Y        28246
NaN      12078
Name: count, dtype: int64
mm_rupt
mm_rupt
N      3624745
NaN      12078
Y         1613
Name: count, dtype: int64
mm_uhyst
mm_uhyst
N      3624778
NaN      12078
Y         1580
Name: count, dtype: int64
mm_aicu
mm_aicu
N      3619223
NaN      12078
Y         7135
Name: count, dtype: int64
mtran
mtran
N      3612475
Y        18785
NaN       7176
Name: count, dtype: int64
dlmp_yy
dlmp_yy
2023    2600684
2024     887205
9999     147594
2022       2953
Name: count, dtype: int64
ab_aven1
ab_aven1
N      3387277
Y       244075
NaN       7084
Name: count, dtype: int64
ab_aven6
ab_aven6
N      3551235
Y        80117
NaN       7084
Name: count, dtype: int64
ab_nicu
ab_nicu
N      3272716
Y       358636
NaN       7084
Name: count, dtype: int64
ab_surf
ab_surf
N      3612921
Y        18431
NaN       7084
Name: count, dtype: int64
ab_anti
ab_anti
N      3563693
Y        67659
NaN       7084
Name: count, dtype: int64
ab_seiz
ab_seiz
N      3630027
NaN       7084
Y         1325
Name: count, dtype: int64
ca_anen
ca_anen
N      3628461
NaN       9637
Y          338
Name: count, dtype: int64
ca_mnsb
ca_mnsb
N      3628321
NaN       9637
Y          478
Name: count, dtype: int64
ca_cchd
ca_cchd
N      3626373
NaN       9637
Y         2426
Name: count, dtype: int64
ca_cdh
ca_cdh
N      3628296
NaN       9637
Y          503
Name: count, dtype: int64
ca_omph
ca_omph
N      3628496
NaN       9637
Y          303
Name: count, dtype: int64
ca_gast
ca_gast
N      3628264
NaN       9637
Y          535
Name: count, dtype: int64
ca_limb
ca_limb
N      3628366
NaN       9637
Y          433
Name: count, dtype: int64
ca_cleft
ca_cleft
N      3626911
NaN       9637
Y         1888
Name: count, dtype: int64
ca_clpal
ca_clpal
N      3628024
NaN       9637
Y          775
Name: count, dtype: int64
ca_down
ca_down
N      3626913
NaN       9637
Y         1886
Name: count, dtype: int64
ca_disor
ca_disor
N      3627097
NaN       9637
Y         1702
Name: count, dtype: int64
ca_hypo
ca_hypo
N      3626957
NaN       9637
Y         1842
Name: count, dtype: int64
itran
itran
N      3589927
Y        42394
NaN       6115
Name: count, dtype: int64
bfed
bfed
Y      2726667
N       479811
NaN     431958
Name: count, dtype: int64
rf_fedrg
rf_fedrg
NaN    3549214
N        60671
Y        28551
Name: count, dtype: int64
rf_artec
rf_artec
NaN    3549214
Y        69722
N        19500
Name: count, dtype: int64
me_trial
me_trial
NaN    2472366
N       837948
Y       328122
Name: count, dtype: int64

## ***Missingness***

In [ ]:
# Determine percentage of missingness by column
missing_rate = raw_data.isna().sum(axis=0).sort_values(ascending=False)
missing_rate_percent = ((missing_rate / len(raw_data)) * 100).round(1)
missing_df = pd.concat([missing_rate, missing_rate_percent], axis = 1, keys = ['count', 'percent'])
missing_df

                count  percent
octerr        3638436    100.0
rcnty_pop     3638436    100.0
rcnty         3638436    100.0
mrterr        3638436    100.0
rectype       3638436    100.0
rcity_pop     3638436    100.0
mrcntry       3638436    100.0
mbcntry       3638436    100.0
ocntyfips     3638436    100.0
ocntypop      3638436    100.0
mage_repflg   3638353    100.0
imp_sex       3638346    100.0
fagerpt_flg   3638229    100.0
mage_impflg   3637733    100.0
imp_plur      3636742    100.0
lmpused       3636337     99.9
mar_imp       3634634     99.9
apgar10r      3593242     98.8
compgst_imp   3579505     98.4
rf_artec      3549214     97.5
rf_fedrg      3549214     97.5
obgest_flg    3458335     95.1
mraceimp      3332745     91.6
me_trial      2472366     68.0
illb_r        1536926     42.2
feduc          458843     12.6
fracehisp      450549     12.4
bfed           431958     11.9
dmar           402966     11.1
mar_p          402966     11.1
ilp_r11        385882     10.6
ilp_r          385882     10.6
fagecomb       363459     10.0
fagerec11      363459     10.0
ilop_r         312592      8.6
ilop_r11       312592      8.6
dlmp_mm        154749      4.3
wtgain         109016      3.0
wtgain_rec     109016      3.0
illb_r11       105516      2.9
bmi_r           88890      2.4
pwgt_r          77596      2.1
precare5        70222      1.9
precare         70222      1.9
meduc           69489      1.9
previs          67725      1.9
previs_rec      67725      1.9
wic             43306      1.2
dwgt_r          39976      1.1
mracehisp       35805      1.0
cig_3           35729      1.0
cig3_r          35729      1.0
pay             30247      0.8
m_ht_in         23642      0.6
tbo_rec         22025      0.6
apgar10         20902      0.6
apgar5          18338      0.5
apgar5r         18338      0.5
cig_0           18039      0.5
cig0_r          18039      0.5
cig_1           17803      0.5
cig1_r          17803      0.5
cig_2           17693      0.5
cig2_r          17693      0.5
priorterm       16925      0.5
lbo_rec         15599      0.4
ip_hepc         14515      0.4
ip_chlam        14515      0.4
ip_syph         14515      0.4
ip_hepb         14515      0.4
ip_gon          14515      0.4
priordead       14291      0.4
mm_aicu         12078      0.3
mm_plac         12078      0.3
mm_uhyst        12078      0.3
mm_mtr          12078      0.3
mm_rupt         12078      0.3
me_pres         10460      0.3
priorlive        9651      0.3
ca_omph          9637      0.3
ca_clpal         9637      0.3
ca_hypo          9637      0.3
ca_down          9637      0.3
ca_limb          9637      0.3
ca_cchd          9637      0.3
ca_cdh           9637      0.3
ca_disor         9637      0.3
ca_cleft         9637      0.3
ca_anen          9637      0.3
ca_mnsb          9637      0.3
ca_gast          9637      0.3
rf_cesarn        7855      0.2
ob_ecvf          7733      0.2
ob_ecvs          7733      0.2
rf_gdiab         7494      0.2
rf_phype         7494      0.2
rf_pdiab         7494      0.2
rf_ghype         7494      0.2
rf_cesar         7494      0.2
rf_ehype         7494      0.2
rf_inftr         7494      0.2
rf_ppterm        7494      0.2
mtran            7176      0.2
ab_aven6         7084      0.2
ab_surf          7084      0.2
ab_seiz          7084      0.2
ab_aven1         7084      0.2
ab_nicu          7084      0.2
ab_anti          7084      0.2
itran            6115      0.2
rdmeth_rec       5157      0.1
me_rout          5157      0.1
oegest_r10       4609      0.1
gestrec10        4609      0.1
combgest         4609      0.1
oegest_comb      4609      0.1
attend           3243      0.1
dbwt             3106      0.1
bwtr12           3106      0.1
ld_chor          2254      0.1
ld_ster          2254      0.1
ld_antb          2254      0.1
ld_indl          2254      0.1
ld_anes          2254      0.1
ld_augm          2254      0.1
dob_tt            666      0.0
bfacil            313      0.0
f_cigs_2            0      0.0
f_cigs_0            0      0.0
f_cigs_1            0      0.0
f_rf_eclamp         0      0.0
f_rf_inft           0      0.0
f_rf_inf_drg        0      0.0
f_rf_inf_art        0      0.0
f_rf_pdiab          0      0.0
f_wtgain            0      0.0
f_pwgt              0      0.0
f_dwgt              0      0.0
f_rf_phyper         0      0.0
f_rf_gdiab          0      0.0
f_rf_ghyper         0      0.0
f_m_ht              0      0.0
restatus            0      0.0
f_mar_p             0      0.0
mrace6              0      0.0
mrace31             0      0.0
mrace15             0      0.0
mhispx              0      0.0
mhisp_r             0      0.0
mbstate_rec         0      0.0
dob_yy              0      0.0
dob_mm              0      0.0
mager9              0      0.0
mager14             0      0.0
mager               0      0.0
bfacil3             0      0.0
dob_wk              0      0.0
f_bfacil            0      0.0
f_meduc             0      0.0
fhisp_r             0      0.0
f_mhisp             0      0.0
f_cigs_3            0      0.0
f_tobaco            0      0.0
f_wic               0      0.0
f_mpcb              0      0.0
f_tpcv              0      0.0
bmi                 0      0.0
cig_rec             0      0.0
f_fhisp             0      0.0
frace15             0      0.0
frace31             0      0.0
frace6              0      0.0
fhispx              0      0.0
f_feduc             0      0.0
no_risks            0      0.0
f_rf_ncesar         0      0.0
f_rf_cesar          0      0.0
f_rf_ppb            0      0.0
dlmp_yy             0      0.0
dplural             0      0.0
pay_rec             0      0.0
f_apgar5            0      0.0
f_mm_mtr            0      0.0
dmeth_rec           0      0.0
f_dmeth_rec         0      0.0
f_mm_               0      0.0
f_mm_aicu           0      0.0
f_mm_uhyst          0      0.0
f_mm_rupt           0      0.0
no_mmorb            0      0.0
f_ob_succ           0      0.0
f_ob_fail           0      0.0
f_ip_gonor          0      0.0
f_ip_syph           0      0.0
f_ip_chlam          0      0.0
f_ip_hepatb         0      0.0
f_ld_indl           0      0.0
f_ld_augm           0      0.0
f_ld_anes           0      0.0
f_ld_chor           0      0.0
f_ld_antb           0      0.0
f_ld_ster           0      0.0
no_lbrdlv           0      0.0
f_me_pres           0      0.0
f_me_rout           0      0.0
f_me_trial          0      0.0
f_ip_hepatc         0      0.0
no_infec            0      0.0
setorder_r          0      0.0
sex                 0      0.0
f_pay_rec           0      0.0
f_pay               0      0.0
f_ab_vent6          0      0.0
f_ab_niuc           0      0.0
f_ab_vent           0      0.0
gestrec3            0      0.0
oegest_r3           0      0.0
bwtr4               0      0.0
f_ab_surfac         0      0.0
f_ab_antibio        0      0.0
f_ab_seiz           0      0.0
no_abnorm           0      0.0
f_ca_menin          0      0.0
f_ca_anen           0      0.0
f_ca_hypos          0      0.0
f_ca_chrom          0      0.0
f_ca_cleftlp        0      0.0
f_ca_limb           0      0.0
f_ca_hernia         0      0.0
f_ca_heart          0      0.0
f_ca_ompha          0      0.0
f_ca_gastro         0      0.0
f_ca_downs          0      0.0
f_ca_cleft          0      0.0
f_bfed              0      0.0
ilive               0      0.0
no_congen           0      0.0
record_id           0      0.0

## ***Distribution Check***

```
# Use this code to check distribution of variables ( as needed)
distr_check = data['cig_0'].value_counts()
distr_percent = ((distr_check / len(data)) * 100).round(1)
distr_df = pd.concat([distr_check, distr_percent], axis = 1, keys = ['count', 'percent'])
print(distr_df)
```

## *Categorical Variables*

In [ ]:
## ----- Binary ----- ##
bincat_vars = ['rf_pdiab', 'rf_gdiab', 'rf_phype', 'rf_ghype', 'rf_ehype', 'rf_ppterm',
                       'mm_mtr', 'mm_plac', 'mm_rupt', 'mm_uhyst', 'mm_aicu','ip_gon', 'ip_syph',
                       'ip_chlam', 'ip_hepb', 'ip_hepc', 'ob_ecvs', 'ob_ecvf', 'ld_indl',
                       'ld_augm', 'ld_ster', 'ld_antb', 'ld_chor', 'ld_anes', 'me_trial',
                       'ab_aven1', 'ab_aven6', 'ab_nicu', 'ab_surf','ab_anti', 'ab_seiz','ca_anen',
                       'ca_mnsb', 'ca_cchd', 'ca_cdh','ca_omph','ca_gast', 'ca_limb', 'ca_cleft',
                       'ca_clpal', 'ca_hypo', 'wic']

## ----- Nominal ----- ##
nomcat_vars = ['mracehisp', 'me_pres', 'me_rout', 'rdmeth_rec']

## ----- Ordinal ----- ##'
ordcat_vars = ['meduc', 'lbo_rec', 'tbo_rec', 'precare']

print('Binary categorical variable count:', len(bincat_vars))
print('Nominal categorical variable count:', len(nomcat_vars))

Binary categorical variable count: 42
Nominal categorical variable count: 4

### *Binary Encoding*

In [ ]:
for col in bincat_vars: # normalize text
  raw_data[col] = raw_data[col].astype(str).str.strip().str.upper()

for col in bincat_vars: # convert to 0/1
  raw_data[col] = (raw_data[col] == 'Y').astype(int)

In [ ]:
for col in bincat_vars: # verify binary encoding
  print(raw_data[col].value_counts())

rf_pdiab
0    3590717
1      47719
Name: count, dtype: int64
rf_gdiab
0    3330863
1     307573
Name: count, dtype: int64
rf_phype
0    3517016
1     121420
Name: count, dtype: int64
rf_ghype
0    3260644
1     377792
Name: count, dtype: int64
rf_ehype
0    3630214
1       8222
Name: count, dtype: int64
rf_ppterm
0    3493369
1     145067
Name: count, dtype: int64
mm_mtr
0    3617296
1      21140
Name: count, dtype: int64
mm_plac
0    3610190
1      28246
Name: count, dtype: int64
mm_rupt
0    3636823
1       1613
Name: count, dtype: int64
mm_uhyst
0    3636856
1       1580
Name: count, dtype: int64
mm_aicu
0    3631301
1       7135
Name: count, dtype: int64
ip_gon
0    3630537
1       7899
Name: count, dtype: int64
ip_syph
0    3625467
1      12969
Name: count, dtype: int64
ip_chlam
0    3578308
1      60128
Name: count, dtype: int64
ip_hepb
0    3632431
1       6005
Name: count, dtype: int64
ip_hepc
0    3625210
1      13226
Name: count, dtype: int64
ob_ecvs
0    3631862
1       6574
Name: count, dtype: int64
ob_ecvf
0    3632227
1       6209
Name: count, dtype: int64
ld_indl
0    2406719
1    1231717
Name: count, dtype: int64
ld_augm
0    2875679
1     762757
Name: count, dtype: int64
ld_ster
0    3507212
1     131224
Name: count, dtype: int64
ld_antb
0    2743375
1     895061
Name: count, dtype: int64
ld_chor
0    3572147
1      66289
Name: count, dtype: int64
ld_anes
1    2841108
0     797328
Name: count, dtype: int64
me_trial
0    3310314
1     328122
Name: count, dtype: int64
ab_aven1
0    3394361
1     244075
Name: count, dtype: int64
ab_aven6
0    3558319
1      80117
Name: count, dtype: int64
ab_nicu
0    3279800
1     358636
Name: count, dtype: int64
ab_surf
0    3620005
1      18431
Name: count, dtype: int64
ab_anti
0    3570777
1      67659
Name: count, dtype: int64
ab_seiz
0    3637111
1       1325
Name: count, dtype: int64
ca_anen
0    3638098
1        338
Name: count, dtype: int64
ca_mnsb
0    3637958
1        478
Name: count, dtype: int64
ca_cchd
0    3636010
1       2426
Name: count, dtype: int64
ca_cdh
0    3637933
1        503
Name: count, dtype: int64
ca_omph
0    3638133
1        303
Name: count, dtype: int64
ca_gast
0    3637901
1        535
Name: count, dtype: int64
ca_limb
0    3638003
1        433
Name: count, dtype: int64
ca_cleft
0    3636548
1       1888
Name: count, dtype: int64
ca_clpal
0    3637661
1        775
Name: count, dtype: int64
ca_hypo
0    3636594
1       1842
Name: count, dtype: int64
wic
0    2488062
1    1150374
Name: count, dtype: int64

## *Numerical Variables*

In [ ]:
## ----- Continuous ----- ##
contnum_vars = ['mager', 'illb_r', 'm_ht_in', 'bmi', 'wtgain', 'combgest']

## ----- Discrete ----- ##
disnum_vars = ['previs', 'cig_0', 'cig_1', 'cig_2', 'cig_3', 'priorlive', 'priordead',
                       'priorterm', 'rf_cesarn', 'apgar5', 'apgar10']

print('Continuous numeric variable count:', len(contnum_vars))
print('Discrete numeric variable count:', len(disnum_vars))

Continuous numeric variable count: 6
Discrete numeric variable count: 11

In [ ]:
display(f'Summary Statistics for Continuous Numeric Variables:', raw_data[contnum_vars].describe())
display(f'Summary Statistics for Discrete Numeric Variables:', raw_data[disnum_vars].describe())

'Summary Statistics for Continuous Numeric Variables:'

,mager,illb_r,m_ht_in,bmi,wtgain,combgest
count,3.638436e+06,2.101510e+06,3.614794e+06,3.638436e+06,3.529420e+06,3.633827e+06
mean,2.967069e+01,4.941228e+01,6.401002e+01,2.966213e+01,2.943477e+01,3.852065e+01
std,5.813960e+00,3.899341e+01,2.866530e+00,1.303674e+01,1.552784e+01,2.482444e+00
min,1.200000e+01,3.000000e+00,3.000000e+01,1.300000e+01,0.000000e+00,1.700000e+01
25%,2.500000e+01,2.400000e+01,6.200000e+01,2.290000e+01,1.900000e+01,3.800000e+01
50%,3.000000e+01,3.600000e+01,6.400000e+01,2.660000e+01,2.800000e+01,3.900000e+01
75%,3.400000e+01,6.300000e+01,6.600000e+01,3.210000e+01,3.800000e+01,4.000000e+01
max,5.000000e+01,3.000000e+02,7.800000e+01,9.990000e+01,9.800000e+01,4.700000e+01

'Summary Statistics for Discrete Numeric Variables:'

,previs,cig_0,cig_1,cig_2,cig_3,priorlive,priordead,priorterm,rf_cesarn,apgar5,apgar10
count,3.570711e+06,3.620397e+06,3.620633e+06,3.620743e+06,3.602707e+06,3.628785e+06,3.624145e+06,3.621511e+06,3.630581e+06,3.620098e+06,3.617534e+06
mean,1.091049e+01,3.834132e-01,2.565979e-01,2.014261e-01,1.802836e-01,1.111960e+00,1.505569e-02,4.497855e-01,2.182359e-01,8.746209e+00,8.697655e+01
std,4.249840e+00,2.967830e+00,2.274918e+00,1.944569e+00,1.833248e+00,1.325674e+00,1.856285e-01,9.269046e-01,5.863987e-01,8.386978e-01,9.103830e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,9.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00,8.800000e+01
50%,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00,8.800000e+01
75%,1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,9.000000e+00,8.800000e+01
max,9.000000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,1.800000e+01,1.800000e+01,3.000000e+01,1.400000e+01,1.000000e+01,8.800000e+01

In [ ]:
display(raw_data[contnum_vars].info())
display(raw_data[disnum_vars].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3638436 entries, 0 to 3638435
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   mager     int64
 1   illb_r    float64
 2   m_ht_in   float64
 3   bmi       float64
 4   wtgain    float64
 5   combgest  float64
dtypes: float64(5), int64(1)
memory usage: 166.6 MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3638436 entries, 0 to 3638435
Data columns (total 11 columns):
 #   Column     Dtype
---  ------     -----
 0   previs     float64
 1   cig_0      float64
 2   cig_1      float64
 3   cig_2      float64
 4   cig_3      float64
 5   priorlive  float64
 6   priordead  float64
 7   priorterm  float64
 8   rf_cesarn  float64
 9   apgar5     float64
 10  apgar10    float64
dtypes: float64(11)
memory usage: 305.3 MB

None

# ***Clustering Data***

## *Create Cluster Dataset*

In [ ]:
# Set cluster data using cluster variables only
cluster_data = raw_data[cluster_vars].copy()

print(f'Shape of Cluster Dataset:', cluster_data.shape)
cluster_data.head()

Shape of Cluster Dataset: (3638436, 34)

,mager,priorlive,priordead,priorterm,rf_cesarn,illb_r,m_ht_in,bmi,wtgain,combgest,previs,cig_0,cig_1,cig_2,cig_3,rf_pdiab,rf_gdiab,rf_phype,rf_ghype,rf_ehype,rf_ppterm,rf_inftr,rf_fedrg,rf_artec,ip_gon,ip_syph,ip_chlam,ip_hepb,ip_hepc,mracehisp,meduc,lbo_rec,tbo_rec,precare
0,30,1.0,0.0,0.0,0.0,30.0,66.0,20.799999,4.0,38.0,8.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,N,NaN,NaN,0,0,0,0,0,2.0,3.0,2.0,2.0,3.0
1,28,0.0,0.0,0.0,0.0,NaN,67.0,20.400000,40.0,38.0,13.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,N,NaN,NaN,0,0,0,0,0,6.0,6.0,1.0,1.0,3.0
2,41,6.0,0.0,2.0,2.0,84.0,67.0,22.700001,28.0,37.0,11.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,N,NaN,NaN,0,0,0,0,0,1.0,6.0,7.0,8.0,2.0
3,29,2.0,0.0,0.0,0.0,49.0,61.0,26.400000,NaN,38.0,10.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,N,NaN,NaN,0,0,0,0,0,1.0,4.0,3.0,3.0,3.0
4,28,1.0,0.0,2.0,0.0,17.0,64.0,21.500000,31.0,39.0,13.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,N,NaN,NaN,0,0,0,0,0,1.0,6.0,2.0,4.0,2.0

In [ ]:
# Remove Inferitlity/Assist. Technology Variables
cluster_data = cluster_data.drop(columns=['rf_inftr', 'rf_artec', 'rf_fedrg'])
print(f'Shape of Cluster Dataset:', cluster_data.shape)
cluster_data.head()

Shape of Cluster Dataset: (3638436, 31)

,mager,priorlive,priordead,priorterm,rf_cesarn,illb_r,m_ht_in,bmi,wtgain,combgest,previs,cig_0,cig_1,cig_2,cig_3,rf_pdiab,rf_gdiab,rf_phype,rf_ghype,rf_ehype,rf_ppterm,ip_gon,ip_syph,ip_chlam,ip_hepb,ip_hepc,mracehisp,meduc,lbo_rec,tbo_rec,precare
0,30,1.0,0.0,0.0,0.0,30.0,66.0,20.799999,4.0,38.0,8.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,2.0,3.0,2.0,2.0,3.0
1,28,0.0,0.0,0.0,0.0,NaN,67.0,20.400000,40.0,38.0,13.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,6.0,6.0,1.0,1.0,3.0
2,41,6.0,0.0,2.0,2.0,84.0,67.0,22.700001,28.0,37.0,11.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,1.0,6.0,7.0,8.0,2.0
3,29,2.0,0.0,0.0,0.0,49.0,61.0,26.400000,NaN,38.0,10.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,1.0,4.0,3.0,3.0,3.0
4,28,1.0,0.0,2.0,0.0,17.0,64.0,21.500000,31.0,39.0,13.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,1.0,6.0,2.0,4.0,2.0

The features pertaining to infertility treatements/drugs, and assisted reproductive technology will not be included as pre-delivery characteristics. They will be excluded because of a partial state-level reporting issues, where the information was inputted incorrectly-- hence vast missing data. However, there is no way to verify which rows came from the affected states. All three columns will be removed.

----

Note this public health data issue in report.

In [ ]:
# missingness
cluster_missing = cluster_data.isna().mean()*100
cluster_missing.sort_values(ascending = False)

illb_r       42.241392
wtgain        2.996232
precare       1.930005
meduc         1.909859
previs        1.861377
mracehisp     0.984077
cig_3         0.981988
m_ht_in       0.649785
tbo_rec       0.605343
cig_0         0.495790
cig_1         0.489304
cig_2         0.486280
priorterm     0.465172
lbo_rec       0.428728
priordead     0.392779
priorlive     0.265251
rf_cesarn     0.215889
combgest      0.126675
mager         0.000000
bmi           0.000000
rf_pdiab      0.000000
rf_phype      0.000000
rf_gdiab      0.000000
ip_syph       0.000000
ip_gon        0.000000
rf_ppterm     0.000000
rf_ehype      0.000000
rf_ghype      0.000000
ip_hepc       0.000000
ip_chlam      0.000000
ip_hepb       0.000000
dtype: float64

## *Imputing NaN Data*

In [ ]:
# Median Impuation
med_impute_vars = disnum_vars + contnum_vars + ordcat_vars
med_impute_vars = [col for col in med_impute_vars if col in cluster_data.columns]

for col in med_impute_vars:
  cluster_data[col] = cluster_data[col].fillna(cluster_data[col].median())

# Verify
cluster_data[med_impute_vars].isna().sum()

previs       0
cig_0        0
cig_1        0
cig_2        0
cig_3        0
priorlive    0
priordead    0
priorterm    0
rf_cesarn    0
mager        0
illb_r       0
m_ht_in      0
bmi          0
wtgain       0
combgest     0
meduc        0
lbo_rec      0
tbo_rec      0
precare      0
dtype: int64

## *One-hot Encoding*

In [ ]:
# Nominal Variable (Race) -- create 'Unknown' for one-hot encoding
cluster_data['mracehisp'] = cluster_data['mracehisp'].fillna('Unknown')

# One-hot encoding for Nominal variable
cluster_data = pd.get_dummies(cluster_data, columns = ['mracehisp'], drop_first = False)

# Convert true/false to 1/0
race_bool_cols = [col for col in cluster_data.columns if 'mracehisp_' in col]
cluster_data[race_bool_cols] = cluster_data[race_bool_cols].astype(int)

# Verify
cluster_data[race_bool_cols].head()

,mracehisp_1.0,mracehisp_2.0,mracehisp_3.0,mracehisp_4.0,mracehisp_5.0,mracehisp_6.0,mracehisp_7.0,mracehisp_Unknown
0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0
2,1,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0

In [ ]:
# Check data types for Cluster Data
print(f' Final Cluster Data Shape:', cluster_data.shape)
cluster_data.info()

 Final Cluster Data Shape: (3638436, 38)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3638436 entries, 0 to 3638435
Data columns (total 38 columns):
 #   Column             Dtype
---  ------             -----
 0   mager              int64
 1   priorlive          float64
 2   priordead          float64
 3   priorterm          float64
 4   rf_cesarn          float64
 5   illb_r             float64
 6   m_ht_in            float64
 7   bmi                float64
 8   wtgain             float64
 9   combgest           float64
 10  previs             float64
 11  cig_0              float64
 12  cig_1              float64
 13  cig_2              float64
 14  cig_3              float64
 15  rf_pdiab           int64
 16  rf_gdiab           int64
 17  rf_phype           int64
 18  rf_ghype           int64
 19  rf_ehype           int64
 20  rf_ppterm          int64
 21  ip_gon             int64
 22  ip_syph            int64
 23  ip_chlam           int64
 24  ip_hepb            int64
 25  ip_hepc            int64
 26  meduc              float64
 27  lbo_rec            float64
 28  tbo_rec            float64
 29  precare            float64
 30  mracehisp_1.0      int64
 31  mracehisp_2.0      int64
 32  mracehisp_3.0      int64
 33  mracehisp_4.0      int64
 34  mracehisp_5.0      int64
 35  mracehisp_6.0      int64
 36  mracehisp_7.0      int64
 37  mracehisp_Unknown  int64
dtypes: float64(18), int64(20)
memory usage: 1.0 GB

In [ ]:
# Final check for missingness in Cluster Data before exporting
cluster_data.isna().sum()

mager                0
priorlive            0
priordead            0
priorterm            0
rf_cesarn            0
illb_r               0
m_ht_in              0
bmi                  0
wtgain               0
combgest             0
previs               0
cig_0                0
cig_1                0
cig_2                0
cig_3                0
rf_pdiab             0
rf_gdiab             0
rf_phype             0
rf_ghype             0
rf_ehype             0
rf_ppterm            0
ip_gon               0
ip_syph              0
ip_chlam             0
ip_hepb              0
ip_hepc              0
meduc                0
lbo_rec              0
tbo_rec              0
precare              0
mracehisp_1.0        0
mracehisp_2.0        0
mracehisp_3.0        0
mracehisp_4.0        0
mracehisp_5.0        0
mracehisp_6.0        0
mracehisp_7.0        0
mracehisp_Unknown    0
dtype: int64

In [ ]:
# Export Cluster Dataset
cluster_data.to_csv('/content/drive/MyDrive/Capstone/cleaned_cluster_data.csv', index = False)

In [ ]:
cluster_data['illb_r'].value_counts()

illb_r
36.0     1568477
22.0       51326
23.0       50093
21.0       49955
25.0       49123
24.0       49052
26.0       47818
20.0       46835
27.0       46463
28.0       44864
3.0        43630
19.0       43494
29.0       43048
30.0       41996
31.0       40318
18.0       39692
32.0       39225
33.0       38204
17.0       36144
34.0       36126
35.0       33759
16.0       32510
37.0       30141
15.0       29591
38.0       28937
39.0       27420
14.0       26946
40.0       26209
41.0       25312
13.0       24158
42.0       24068
43.0       23316
44.0       22343
45.0       21820
12.0       21263
46.0       20698
47.0       19737
48.0       19250
49.0       18798
50.0       18375
51.0       17689
52.0       17373
53.0       16739
54.0       16238
55.0       15886
56.0       15495
57.0       15461
11.0       14954
58.0       14760
59.0       13973
60.0       13693
61.0       12883
62.0       12693
63.0       12283
64.0       12057
65.0       11683
66.0       11533
67.0       11195
68.0       10918
69.0       10809
70.0       10420
71.0       10119
72.0        9939
73.0        9583
74.0        9309
76.0        8980
75.0        8980
77.0        8748
78.0        8459
79.0        8388
80.0        8155
81.0        8115
82.0        7884
83.0        7566
84.0        7355
85.0        7163
86.0        7014
87.0        6790
10.0        6654
88.0        6638
89.0        6604
91.0        6332
90.0        6253
92.0        6194
93.0        6093
94.0        5946
95.0        5720
96.0        5633
97.0        5529
98.0        5349
100.0       5196
99.0        5171
102.0       5003
101.0       4874
103.0       4773
104.0       4750
105.0       4616
106.0       4614
107.0       4394
108.0       4367
109.0       4147
110.0       4120
111.0       4079
114.0       3846
112.0       3768
113.0       3744
115.0       3721
117.0       3606
116.0       3574
118.0       3512
119.0       3426
120.0       3251
121.0       3166
122.0       3079
123.0       3005
125.0       2948
124.0       2945
126.0       2784
129.0       2721
127.0       2672
128.0       2604
130.0       2494
131.0       2472
132.0       2442
9.0         2440
136.0       2310
133.0       2303
134.0       2298
135.0       2289
137.0       2184
140.0       2173
139.0       2140
138.0       2116
141.0       2042
142.0       1973
143.0       1947
145.0       1923
144.0       1902
147.0       1807
146.0       1796
150.0       1754
148.0       1745
149.0       1739
151.0       1726
152.0       1617
153.0       1548
154.0       1512
156.0       1497
155.0       1490
157.0       1421
158.0       1415
160.0       1364
159.0       1349
161.0       1297
162.0       1278
163.0       1278
166.0       1216
164.0       1199
165.0       1196
168.0       1162
167.0       1127
169.0       1095
8.0         1090
174.0       1088
170.0       1033
171.0       1015
172.0        994
175.0        988
173.0        980
176.0        931
179.0        919
177.0        917
180.0        877
181.0        864
182.0        857
178.0        855
183.0        783
184.0        776
186.0        775
7.0          771
188.0        747
189.0        734
185.0        732
187.0        695
6.0          677
191.0        666
190.0        658
193.0        618
192.0        611
194.0        603
195.0        583
199.0        560
196.0        553
197.0        542
198.0        535
203.0        520
201.0        499
5.0          487
204.0        481
200.0        481
205.0        465
202.0        465
206.0        419
209.0        412
4.0          411
211.0        394
208.0        389
207.0        381
214.0        362
210.0        358
300.0        348
212.0        347
213.0        329
215.0        326
216.0        312
218.0        293
220.0        291
217.0        277
222.0        264
219.0        258
221.0        252
223.0        246
224.0        242
225.0        236
229.0        220
226.0        219
230.0        216
228.0        211
232.0        206
227.0        193
231.0        185
233.0        185
234.0        163
238.0        163
236.0        161
235.0        158
237.0        149
240.0        146
242.0        141
245.0        132
239.0        132
246.0        128
251.0        125
241.0        124
243.0        118
244.0        116
247.0        108
250.0        106
248.0         97
249.0         97
255.0         94
252.0         89
259.0         89
254.0         87
260.0         87
253.0         86
256.0         85
262.0         84
264.0         84
263.0         79
257.0         77
258.0         69
265.0         63
282.0         63
266.0         63
278.0         61
277.0         59
261.0         58
269.0         57
270.0         57
274.0         54
286.0         54
275.0         53
271.0         51
267.0         49
284.0         46
279.0         46
272.0         46
280.0         45
283.0         44
268.0         44
288.0         44
273.0         43
276.0         42
281.0         42
287.0         41
285.0         40
292.0         38
290.0         33
294.0         30
295.0         27
289.0         27
296.0         23
293.0         23
291.0         23
297.0         20
299.0         18
298.0         15
Name: count, dtype: int64

# ***Outcome Data***

In [ ]:
morb_outcome_data = raw_data[morbidity_vars].copy()
print(f'Shape of Morbidity Outcome Dataset:', morb_outcome_data.shape)
display(morb_outcome_data.info())

Shape of Morbidity Outcome Dataset: (3638436, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3638436 entries, 0 to 3638435
Data columns (total 5 columns):
 #   Column    Dtype
---  ------    -----
 0   mm_mtr    int64
 1   mm_plac   int64
 2   mm_rupt   int64
 3   mm_uhyst  int64
 4   mm_aicu   int64
dtypes: int64(5)
memory usage: 138.8 MB

None

In [ ]:
morb_outcome_data.isna().sum()

mm_mtr      0
mm_plac     0
mm_rupt     0
mm_uhyst    0
mm_aicu     0
dtype: int64

In [ ]:
# Export morbidity outcome dataset
morb_outcome_data.to_csv('/content/drive/MyDrive/Capstone/cleaned_morbidity_outcome_data.csv', index = False)

# ***Clustering + Outcome Data***

In [ ]:
cleaned_complete_dataset = pd.concat([cluster_data, morb_outcome_data], axis = 1)
print(f'Shape of Complete Dataset:', cleaned_complete_dataset.shape)
display(cleaned_complete_dataset.head())

Shape of Complete Dataset: (3638436, 43)

,mager,priorlive,priordead,priorterm,rf_cesarn,illb_r,m_ht_in,bmi,wtgain,combgest,previs,cig_0,cig_1,cig_2,cig_3,rf_pdiab,rf_gdiab,rf_phype,rf_ghype,rf_ehype,rf_ppterm,ip_gon,ip_syph,ip_chlam,ip_hepb,ip_hepc,meduc,lbo_rec,tbo_rec,precare,mracehisp_1.0,mracehisp_2.0,mracehisp_3.0,mracehisp_4.0,mracehisp_5.0,mracehisp_6.0,mracehisp_7.0,mracehisp_Unknown,mm_mtr,mm_plac,mm_rupt,mm_uhyst,mm_aicu
0,30,1.0,0.0,0.0,0.0,30.0,66.0,20.799999,4.0,38.0,8.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,3.0,2.0,2.0,3.0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,28,0.0,0.0,0.0,0.0,36.0,67.0,20.400000,40.0,38.0,13.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,6.0,1.0,1.0,3.0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,41,6.0,0.0,2.0,2.0,84.0,67.0,22.700001,28.0,37.0,11.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,6.0,7.0,8.0,2.0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,29,2.0,0.0,0.0,0.0,49.0,61.0,26.400000,28.0,38.0,10.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,4.0,3.0,3.0,3.0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,28,1.0,0.0,2.0,0.0,17.0,64.0,21.500000,31.0,39.0,13.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,6.0,2.0,4.0,2.0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
cleaned_complete_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3638436 entries, 0 to 3638435
Data columns (total 43 columns):
 #   Column             Dtype
---  ------             -----
 0   mager              int64
 1   priorlive          float64
 2   priordead          float64
 3   priorterm          float64
 4   rf_cesarn          float64
 5   illb_r             float64
 6   m_ht_in            float64
 7   bmi                float64
 8   wtgain             float64
 9   combgest           float64
 10  previs             float64
 11  cig_0              float64
 12  cig_1              float64
 13  cig_2              float64
 14  cig_3              float64
 15  rf_pdiab           int64
 16  rf_gdiab           int64
 17  rf_phype           int64
 18  rf_ghype           int64
 19  rf_ehype           int64
 20  rf_ppterm          int64
 21  ip_gon             int64
 22  ip_syph            int64
 23  ip_chlam           int64
 24  ip_hepb            int64
 25  ip_hepc            int64
 26  meduc              float64
 27  lbo_rec            float64
 28  tbo_rec            float64
 29  precare            float64
 30  mracehisp_1.0      int64
 31  mracehisp_2.0      int64
 32  mracehisp_3.0      int64
 33  mracehisp_4.0      int64
 34  mracehisp_5.0      int64
 35  mracehisp_6.0      int64
 36  mracehisp_7.0      int64
 37  mracehisp_Unknown  int64
 38  mm_mtr             int64
 39  mm_plac            int64
 40  mm_rupt            int64
 41  mm_uhyst           int64
 42  mm_aicu            int64
dtypes: float64(18), int64(25)
memory usage: 1.2 GB

In [ ]:
# Export full dataset
cleaned_complete_dataset.to_csv('/content/drive/MyDrive/Capstone/cleaned_complete_dataset.csv', index = False)